# Mapping of config files to their target paths in /data/plugins/
# Format: "target/path/file.ext": "source-file.yml"

configs:
  core_plugin/api_config.yaml: api_config.yaml
  # Add more configs as needed:
  # SomePlugin/settings.json: some-plugin-settings.yml
  # AnotherPlugin/data/config.txt: another-config.yml

