image:
  repository: josxha/minecraft-purpur
  tag: 1.21.5
  pullPolicy: IfNotPresent

version: "1.21.5"

replicaCount: 1

service:
  type: ClusterIP
  port: 25565
  headless: true

jvm:
  opts: "-Xms1g -Xmx3g -XX:+UseG1GC -XX:MaxGCPauseMillis=75 -Dfile.encoding=UTF-8"

resources:
  requests:
    cpu: "1000m"
    memory: "3Gi"
  limits:
    cpu: "1"
    memory: "4Gi"

health:
  port: 8080

velocity:
  forwardingSecret: "minecraft-secret-key"
  allowedNamespaceLabel: "app.kubernetes.io/name=velocity"

server:
  onlineMode: false
  velocity:
    enabled: true
    secret: "minecraft-secret-key"
    forwardingMode: "modern"

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""
  shared: true
  hostPath:
    path: "/var/lib/minecraft/purpur-lobby-world"
    nodeName: ""

plugins:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
  list:
    - name: gr-core-plugin
      type: github
      repository: BryuggemanNikita/gr-core-plugin
      version: develop
      artifact: gr-core-plugin-1.0.0.jar
    - name: gr-player-plugin
      type: github
      repository: BryuggemanNikita/gr-player-plugin
      version: develop
      artifact: gr-player-plugin-1.0.0.jar
    - name: gr-race-plugin
      type: github
      repository: BryuggemanNikita/gr-race-plugin
      version: develop
      artifact: gr-race-plugin-1.0.0.jar
    - name: ProtocolLib
      type: url
      url: https://github.com/dmulloy2/ProtocolLib/releases/download/5.4.0/ProtocolLib.jar

plugin:
  enabled: false
  name: "purpur-plugin-1.0.0.jar"
  config:
    economy:
      url: "http://economy-api:8080"
      timeout: 5000
    redis:
      host: "redis"
      port: 6379
      timeout: 5000

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

nodeSelector: {}

