image:
  repository: josxha/minecraft-purpur
  tag: 1.21.5
  pullPolicy: IfNotPresent

version: "1.21.5"

replicaCount: 1

service:
  type: ClusterIP
  port: 25565
  headless: true

jvm:
  opts: "-Xms1g -Xmx3g -XX:+UseG1GC -XX:MaxGCPauseMillis=75 -Dfile.encoding=UTF-8"

resources:
  requests:
    cpu: "1000m"
    memory: "3Gi"
  limits:
    cpu: "1"
    memory: "4Gi"

health:
  port: 8080

server:
  onlineMode: false
  velocity:
    enabled: true
    secret: "minecraft-secret-key"
    forwardingMode: "modern"
  properties:
    difficulty: easy
    gamemode: survival
    maxPlayers: 20
    viewDistance: 10
    simulationDistance: 10
    spawnMonsters: false
    spawnAnimals: true
    pvp: false
    allowFlight: false
    allowNether: true
    generateStructures: true
    levelType: "minecraft:normal"
    motd: "A Minecraft Server"
  spigot:
    restartOnCrash: true
    movedTooQuicklyMultiplier: 10.0
    movedWronglyThreshold: 0.0625
    timeoutTime: 60
    nettyThreads: 4
  # Custom overrides applied on top of auto-generated configs
  overrides:
    serverProperties: |
      # Custom server.properties overrides
      # These will be appended to server.properties after Purpur generates it
    spigotYml: |
      # Custom spigot.yml overrides (YAML format)
      # Example:
      # world-settings:
      #   default:
      #     mob-spawn-range: 6
      #     view-distance: 8

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""
  shared: true

plugins:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
  list:
    - name: gr-core-plugin
      type: github
      repository: BryuggemanNikita/gr-core-plugin
      version: develop
      artifact: gr-core-plugin-1.0.0.jar
    - name: gr-player-plugin
      type: github
      repository: BryuggemanNikita/gr-player-plugin
      version: develop
      artifact: gr-player-plugin-1.0.0.jar
    - name: gr-race-plugin
      type: github
      repository: BryuggemanNikita/gr-race-plugin
      version: develop
      artifact: gr-race-plugin-1.0.0.jar
    - name: ProtocolLib
      type: url
      url: https://github.com/dmulloy2/ProtocolLib/releases/download/5.4.0/ProtocolLib.jar


tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

nodeSelector: {}

