image:
  repository: itzg/minecraft-server
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 6Gi

persistence:
  enabled: true
  size: 20Gi
  storageClass: local-path

service:
  type: ClusterIP
  port: 25565

env:
  TYPE: "PURPUR"
  EULA: "TRUE"
  ENABLE_RCON: "false"
  ONLINE_MODE: "true"
  MEMORY: "4G"

networkPolicy:
  enabled: true

podDisruptionBudget:
  enabled: true

hpa:
  enabled: false


