{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.shared }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "purpur-shard.fullname" . }}-shared-world
  labels:
    app.kubernetes.io/name: {{ include "purpur-shard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "purpur-shard.fullname" . }}-world
  labels:
    app.kubernetes.io/name: {{ include "purpur-shard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
