apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "velocity.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "velocity.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "velocity.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "velocity.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      initContainers:
        - name: copy-config
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args: ["cp -f /config/* /data/ 2>/dev/null || true"]
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      containers:
        - name: velocity
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /data
          ports:
            - name: mc
              containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "velocity.fullname" . }}-config
            items:
              - key: velocity.toml
                path: velocity.toml
              - key: forwarding.secret
                path: forwarding.secret
        - name: data
          emptyDir: {}

