apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity
  labels:
    app: velocity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
        runAsGroup: 1000
      initContainers:
      - name: init-perms
        image: alpine:3.20
        command: ["/bin/sh","-c"]
        args: ["mkdir -p /endkind /server && chmod 0777 /endkind /server"]
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: endkind
          mountPath: /endkind
        - name: data
          mountPath: /server
      containers:
      - name: velocity
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 25565
          name: mc
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        - name: data
          mountPath: /server
        - name: velocity-config
          mountPath: /server/velocity.toml
          subPath: velocity.toml
        - name: velocity-secret
          mountPath: /server/forwarding.secret
          subPath: forwarding.secret
        - name: endkind
          mountPath: /endkind
        resources:
{{ toYaml .Values.resources | indent 10 }}
        livenessProbe:
          tcpSocket:
            port: mc
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: mc
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop: ["ALL"]
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: velocity-data
      - name: velocity-config
        configMap:
          name: velocity-config
      - name: velocity-secret
        secret:
          secretName: velocity-secret
      - name: endkind
        emptyDir: {}


