apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity
  labels:
    app: velocity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
        runAsGroup: 1000
        fsGroupChangePolicy: Always
      initContainers:
      - name: copy-config
        image: busybox:1.36
        command: ["/bin/sh","-c"]
        args: ["cp -f /config/* /data/ 2>/dev/null || true; cp -f /secret/* /data/ 2>/dev/null || true"]
        volumeMounts:
        - name: cfg
          mountPath: /config
        - name: secret
          mountPath: /secret
        - name: data
          mountPath: /data
      # no endkind; work purely from /data as in old infra
      containers:
      - name: velocity
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: /data
        ports:
        - containerPort: 25565
          name: mc
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        - name: cfg
          mountPath: /config
        - name: secret
          mountPath: /secret
        - name: endkind
          mountPath: /endkind
        # no /endkind mount
        resources:
{{ toYaml .Values.resources | indent 10 }}
        livenessProbe:
          tcpSocket:
            port: mc
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: mc
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop: ["ALL"]
      volumes:
      - name: data
        emptyDir: {}
      - name: cfg
        configMap:
          name: velocity-config
      - name: secret
        secret:
          secretName: velocity-secret
      - name: endkind
        emptyDir: {}
      # no endkind volume


