{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: velocity-allow-ingress-from-nginx
spec:
  podSelector:
    matchLabels:
      app: velocity
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: minecraft
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 25565
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: minecraft
      podSelector:
        matchLabels:
          app: purpur
    ports:
    - protocol: TCP
      port: 25565
{{- end }}


