{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: velocity-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: velocity
{{- end }}


