image:
  repository: nginx
  tag: 1.25-alpine
  pullPolicy: IfNotPresent

service:
  type: NodePort
  httpPort: 80
  httpNodePort: 30080
  mcPort: 25565
  mcNodePort: 30065

routes:
  http:
    # Пример: проксировать /artifactory → сервис artifactory
    - path: /
      service: artifactory
      port: 80

  tcp:
    # Маршрут Minecraft TCP к Velocity сервису на 25565
    - port: 25565
      service: velocity
      servicePort: 25565

