apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "minio.fullname" . }}-pv
  labels:
    app.kubernetes.io/name: {{ include "minio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  hostPath:
    path: {{ .Values.persistence.hostPath.path | quote }}

