sleep:
    # Как быстро игрок устает, когда не спит (бодрствует).
    decrease_rate_per_second: 0.00013889

    # Как быстро игрок отдыхает, когда спит.
    increase_rate_per_second: 0.00111111

    # Порог, при котором начинают применяться дебаффы (например, Замедление 1).
    debuff_threshold: 0.0

    # Порог, при котором дебаффы усиливаются (например, Замедление 2).
    # Должен быть меньше, чем debuff_threshold.
    # Можно использовать отрицательные значения, если нужно, чтобы дебафф
    # применялся некоторое время после полного истощения.
    heavy_debuff_threshold: -0.2

thirst:
    # Как быстро игрок испытывает жажду.
    # Значение 0.004 примерно в 2 раза быстрее, чем стандартный расход голода при беге.
    decrease_rate_per_second: 0.004

    # Количество жажды, которое восстанавливает одна бутылка воды (1.0 = вся шкала).
    water_bottle_heal_amount: 0.3

    dehydration:
        # Количество урона, наносимого игроку периодически (1.0 = полсердца).
        damage_amount: 1.0

        # Интервал в тиках, с которым наносится урон (20 тиков = 1 секунда). Ванильный голод - 80.
        damage_interval_ticks: 80

        # Длительность эффекта Слабости в тиках.
        weakness_duration_ticks: 120

        # Длительность эффекта Слепоты в тиках.
        blindness_duration_ticks: 60

    # Множитель жажды в определенных биомах.
    biome_modifiers:
        # Во сколько раз быстрее будет уходить жажда в указанных биомах.
        multiplier: 2.0

        # Список биомов, в которых жажда будет уходить быстрее.
        biomes:
            - "biome.minecraft.desert"
            - "biome.minecraft.badlands"

health:

    # Максимальное здоровье для активации восстановления (дефолт 3 сердца)
    max_for_healing: 6.0

    # Количество здоровья, которое восстанавливает палка (дефолт 2 сердца)
    heal_amount: 4.0


# Как часто (в тиках) обновляется полоса усталости и проверяются дебаффы.
update_interval_ticks: 10

