# Тут пока будут лежать базовые хар-тики рас
human:
 jump_height: 1
 sizes: 1
 speed:
  night: 1
  day: 1

elf:
 jump_height: 1.25
 sizes: 1.25
 speed:
  night: 1.12
  day: 1.07

zoomorph:
 jump_height: 1.25
 sizes: 1
 speed:
  night: 1
  day: 1

tiefling:
 jump_height: 1
 sizes: 1
 speed:
  night: 1
  day: 1

dwarf:
 jump_height: 1
 sizes: 0.75
 speed:
  night: 0.95
  day: 0.95

