controller:
  replicaCount: 2
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
  metrics:
    enabled: false
  extraArgs:
    tcp-services-configmap: "minecraft/tcp-services"
  ingressClassResource:
    name: nginx
    default: true
  allowSnippetAnnotations: false


