apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "purpur.fullname" . }}-config
data:
  paper-global.yml: |
    proxies:
      velocity:
        enabled: {{ .Values.server.velocity.enabled | default true }}
        online-mode: {{ .Values.server.onlineMode | default false }}
        secret: {{ .Values.server.velocity.secret | quote }}
  spigot.yml: |
    settings:
      debug: {{ .Values.server.spigot.settings.debug | default false }}
      bungeecord: {{ .Values.server.spigot.settings.bungeecord | default false }}
      sample-count: 12
      save-user-cache-on-stop-only: false
      player-shuffle: 0
      user-cache-size: 1000
      netty-threads: {{ .Values.server.spigot.settings.nettyThreads | default 4 }}
      moved-too-quickly-multiplier: {{ .Values.server.spigot.settings.movedTooQuicklyMultiplier | default 10.0 }}
      moved-wrongly-threshold: {{ .Values.server.spigot.settings.movedWronglyThreshold | default 0.0625 }}
      timeout-time: {{ .Values.server.spigot.settings.timeoutTime | default 60 }}
      restart-on-crash: {{ .Values.server.spigot.settings.restartOnCrash | default true }}
      restart-script: ./start.sh
      log-villager-deaths: {{ .Values.server.spigot.settings.logVillagerDeaths | default true }}
      log-named-deaths: {{ .Values.server.spigot.settings.logNamedDeaths | default true }}
      attribute:
        maxAbsorption:
          max: 2048.0
        maxHealth:
          max: 1024.0
        movementSpeed:
          max: 1024.0
        attackDamage:
          max: 2048.0
    messages:
      whitelist: You are not whitelisted on this server!
      unknown-command: Unknown command. Type "/help" for help.
      server-full: The server is full!
      outdated-client: Outdated client! Please use {0}
      outdated-server: Outdated server! I'm still on {0}
      restart: Server is restarting
    advancements:
      disable-saving: false
      disabled:
      - minecraft:story/disabled
    world-settings:
      default:
        below-zero-generation-in-existing-chunks: true
        enable-zombie-pigmen-portal-spawns: true
        zombie-aggressive-towards-villager: true
        end-portal-sound-radius: 0
        wither-spawn-sound-radius: 0
        hanging-tick-frequency: 100
        dragon-death-sound-radius: 0
        merge-radius:
          item: 0.5
          exp: -1.0
        hunger:
          jump-walk-exhaustion: 0.05
          jump-sprint-exhaustion: 0.2
          combat-exhaustion: 0.1
          regen-exhaustion: 6.0
          swim-multiplier: 0.01
          sprint-multiplier: 0.1
          other-multiplier: 0.0
        ticks-per:
          hopper-transfer: 8
          hopper-check: 1
        hopper-amount: 1
        hopper-can-load-chunks: false
        arrow-despawn-rate: {{ .Values.server.spigot.worldSettings.arrowDespawnRate | default 1200 }}
        trident-despawn-rate: 1200
        item-despawn-rate: {{ .Values.server.spigot.worldSettings.itemDespawnRate | default 6000 }}
        mob-spawn-range: {{ .Values.server.spigot.worldSettings.mobSpawnRange | default 8 }}
        nerf-spawner-mobs: {{ .Values.server.spigot.worldSettings.nerfSpawnerMobs | default false }}
        thunder-chance: 100000
        unload-frozen-chunks: false
        growth:
          cactus-modifier: 100
          cane-modifier: 100
          melon-modifier: 100
          mushroom-modifier: 100
          pumpkin-modifier: 100
          sapling-modifier: 100
          beetroot-modifier: 100
          carrot-modifier: 100
          potato-modifier: 100
          torchflower-modifier: 100
          wheat-modifier: 100
          netherwart-modifier: 100
          vine-modifier: 100
          cocoa-modifier: 100
          bamboo-modifier: 100
          sweetberry-modifier: 100
          kelp-modifier: 100
          twistingvines-modifier: 100
          weepingvines-modifier: 100
          cavevines-modifier: 100
          glowberry-modifier: 100
          pitcherplant-modifier: 100
        entity-activation-range:
          animals: {{ .Values.server.spigot.worldSettings.entityActivationRange.animals | default 32 }}
          monsters: {{ .Values.server.spigot.worldSettings.entityActivationRange.monsters | default 32 }}
          raiders: {{ .Values.server.spigot.worldSettings.entityActivationRange.raiders | default 64 }}
          misc: {{ .Values.server.spigot.worldSettings.entityActivationRange.misc | default 16 }}
          water: {{ .Values.server.spigot.worldSettings.entityActivationRange.water | default 16 }}
          villagers: {{ .Values.server.spigot.worldSettings.entityActivationRange.villagers | default 32 }}
          flying-monsters: 32
          wake-up-inactive:
            animals-max-per-tick: 4
            animals-every: 1200
            animals-for: 100
            monsters-max-per-tick: 8
            monsters-every: 400
            monsters-for: 100
            villagers-max-per-tick: 4
            villagers-every: 600
            villagers-for: 100
            flying-monsters-max-per-tick: 8
            flying-monsters-every: 200
            flying-monsters-for: 100
          villagers-work-immunity-after: 100
          villagers-work-immunity-for: 20
          villagers-active-for-panic: true
          tick-inactive-villagers: true
          ignore-spectators: false
        seed-village: 10387312
        seed-desert: 14357617
        seed-igloo: 14357618
        seed-jungle: 14357619
        seed-swamp: 14357620
        seed-monument: 10387313
        seed-shipwreck: 165745295
        seed-ocean: 14357621
        seed-outpost: 165745296
        seed-endcity: 10387313
        seed-slime: 987234911
        seed-nether: 30084232
        seed-mansion: 10387319
        seed-fossil: 14357921
        seed-portal: 34222645
        seed-ancientcity: 20083232
        seed-trailruins: 83469867
        seed-trialchambers: 94251327
        seed-buriedtreasure: 10387320
        seed-mineshaft: default
        seed-stronghold: default
        max-tnt-per-tick: 100
        max-tick-time:
          tile: 50
          entity: 50
        entity-tracking-range:
          players: 128
          animals: 96
          monsters: 96
          misc: 96
          display: 128
          other: 64
        view-distance: {{ .Values.server.spigot.worldSettings.viewDistance | default "default" }}
        simulation-distance: {{ .Values.server.spigot.worldSettings.simulationDistance | default "default" }}
        verbose: false
    players:
      disable-saving: false
    config-version: 12
    commands:
      tab-complete: 0
      send-namespaced: true
      log: true
      replace-commands:
      - setblock
      - summon
      - testforblock
      - tellraw
      spam-exclusions:
      - /skill
      silent-commandblock-console: false
      enable-spam-exclusions: false
    stats:
      disable-saving: false
      forced-stats: {}
  server.properties: |
    # Generated from values.yaml
    difficulty={{ .Values.server.properties.difficulty | default "easy" }}
    gamemode={{ .Values.server.properties.gamemode | default "survival" }}
    max-players={{ .Values.server.properties.maxPlayers | default 20 }}
    view-distance={{ .Values.server.properties.viewDistance | default 10 }}
    simulation-distance={{ .Values.server.properties.simulationDistance | default 10 }}
    spawn-monsters={{ .Values.server.properties.spawnMonsters | default false }}
    spawn-animals={{ .Values.server.properties.spawnAnimals | default true }}
    pvp={{ .Values.server.properties.pvp | default false }}
    allow-flight={{ .Values.server.properties.allowFlight | default false }}
    allow-nether={{ .Values.server.properties.allowNether | default true }}
    generate-structures={{ .Values.server.properties.generateStructures | default true }}
    level-type={{ .Values.server.properties.levelType | default "minecraft:normal" }}
    motd={{ .Values.server.properties.motd | default "A Minecraft Server" }}
    online-mode={{ .Values.server.onlineMode | default false }}

