apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "purpur.fullname" . }}-config
data:
  paper-global.yml: |
    verbose: false
  spigot.yml: |
    settings:
      restart-on-crash: true
  server.properties: |
    online-mode={{ .Values.server.onlineMode | default false }}
    velocity-support=true
    velocity-secret={{ .Values.server.velocity.secret }}

