apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "purpur.fullname" . }}-config
data:
  paper-global.yml: |
    proxies:
      velocity:
        enabled: {{ .Values.server.velocity.enabled | default true }}
        online-mode: {{ .Values.server.onlineMode | default false }}
        secret: {{ .Values.server.velocity.secret | quote }}
  {{- if .Values.server.overrides }}
  server-overrides.properties: |
{{ .Values.server.overrides.serverProperties | indent 4 }}
  spigot-overrides.yml: |
{{ .Values.server.overrides.spigotYml | indent 4 }}
  {{- end }}

