apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "purpur.fullname" . }}
  labels:
    {{- include "purpur.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "purpur.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "purpur.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/configs: {{ include (print $.Template.BasePath "/configs-cm.yaml") . | sha256sum }}
        checksum/plugins: {{ include (print $.Template.BasePath "/plugins-config.yaml") . | sha256sum }}
        plugins-sync-trigger: {{ now | date "20060102-150405" }}
    spec:
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: false
        fsGroup: 10001
      initContainers:
        - name: copy-configs
          image: alpine:3.19
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache yq >/dev/null 2>&1
              echo "=== Applying configs from mapping ==="
              
              MAP="/mapping/mapping.yaml"
              if [ ! -f "$MAP" ]; then
                echo "configs-map.yaml not found, skipping"
                exit 0
              fi
              
              # Read each mapping and copy files
              yq -r '.configs | to_entries | .[] | .key + " " + .value' "$MAP" | while read TARGET SOURCE; do
                if [ -f "/configs/$SOURCE" ]; then
                  mkdir -p "/data/$(dirname $TARGET)"
                  cp "/configs/$SOURCE" "/data/$TARGET"
                  echo "✓ Copied $SOURCE -> /data/$TARGET"
                else
                  echo "✗ Source not found: $SOURCE"
                fi
              done
              
              echo "Config files applied"
          volumeMounts:
            - name: world
              mountPath: /data
            - name: configs
              mountPath: /configs
            - name: configs-map
              mountPath: /mapping
      containers:
        - name: purpur
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.jvm.opts }}"
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PURPUR"
            - name: VERSION
              value: "{{ .Values.version }}"
          ports:
            - name: mc
              containerPort: 25565
              protocol: TCP
            - name: health
              containerPort: {{ .Values.health.port }}
              protocol: TCP
          volumeMounts:
            - name: world
              mountPath: /data
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    echo "save-all" | nc -w 5 localhost 25565 || true
                    sleep 5
                    echo "stop" | nc -w 5 localhost 25565 || true
                    sleep 10
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: world
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "purpur.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: configs
          configMap:
            name: {{ include "purpur.fullname" . }}-configs
        - name: configs-map
          configMap:
            name: {{ include "purpur.fullname" . }}-configs-map
        - name: plugins-config
          configMap:
            name: {{ include "purpur.fullname" . }}-plugins

