{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: purpur-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: purpur
{{- end }}


