apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "purpur.fullname" . }}-plugins-sync-{{ now | date "20060102-150405" }}
  labels:
    {{- include "purpur.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "purpur.name" . }}-plugins-sync
    spec:
      restartPolicy: OnFailure
      containers:
        - name: plugins-sync
          image: alpine:3.19
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-access-token
                  key: token
                  optional: true
          command: ["/bin/sh"]
          args:
            - -c
            - |
              set -e
              apk add --no-cache curl wget yq jq >/dev/null 2>&1
              
              mkdir -p /data/plugins
              PLUGINS_CONFIG="/config/plugins.yaml"
              
              if [ ! -f "$PLUGINS_CONFIG" ]; then
                echo "plugins.yaml not found, skipping"
                exit 0
              fi
              
              echo "=== Syncing plugins from $PLUGINS_CONFIG ==="
              
              download_file() {
                URL="$1"; OUT="$2"
                echo "→ Downloading: $URL"
                rm -f "$OUT" 2>/dev/null || true
                # For GitHub URLs, always use token if available (works for private repos)
                if [ -n "$GITHUB_TOKEN" ]; then
                  echo "  Using GitHub token (${#GITHUB_TOKEN} chars)"
                  curl -fsSL -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/octet-stream" -o "$OUT" "$URL" || { echo "✗ Failed: $URL"; return 1; }
                else
                  echo "  No token available, using anonymous download"
                  curl -fsSL -o "$OUT" "$URL" || { echo "✗ Failed: $URL"; return 1; }
                fi
                if [ -f "$OUT" ] && [ -s "$OUT" ]; then
                  echo "✓ Saved: $OUT"
                else
                  echo "✗ Empty file: $OUT"
                  return 1
                fi
              }
              
              COUNT=$(yq '.plugins | length' "$PLUGINS_CONFIG")
              echo "Found $COUNT plugins in config"
              
              # Build list of expected plugin files
              EXPECTED_PLUGINS=""
              i=0
              while [ "$i" -lt "$COUNT" ]; do
                NAME=$(yq -r ".plugins[$i].name" "$PLUGINS_CONFIG")
                EXPECTED_PLUGINS="$EXPECTED_PLUGINS${NAME}.jar "
                i=$((i+1))
              done
              echo "Expected plugins: $EXPECTED_PLUGINS"
              
              # Remove plugins not in the list
              echo "=== Cleaning up old plugins ==="
              for jar in /data/plugins/*.jar; do
                if [ -f "$jar" ]; then
                  BASENAME=$(basename "$jar")
                  if ! echo "$EXPECTED_PLUGINS" | grep -q "$BASENAME"; then
                    echo "✗ Removing: $BASENAME (not in plugins.yaml)"
                    rm -f "$jar"
                  fi
                fi
              done
              
              # Download plugins
              echo "=== Downloading plugins ==="
              i=0
              while [ "$i" -lt "$COUNT" ]; do
                NAME=$(yq -r ".plugins[$i].name" "$PLUGINS_CONFIG")
                TYPE=$(yq -r ".plugins[$i].type" "$PLUGINS_CONFIG")
                
                echo "[$i] Processing: $NAME (type: $TYPE)"
                
                if [ "$TYPE" = "github" ]; then
                  REPO=$(yq -r ".plugins[$i].repository" "$PLUGINS_CONFIG")
                  VERSION=$(yq -r ".plugins[$i].version" "$PLUGINS_CONFIG")
                  ARTIFACT=$(yq -r ".plugins[$i].artifact" "$PLUGINS_CONFIG")
                  
                  # Get release by tag (works for both 'latest' and specific tags)
                  if [ "$VERSION" = "latest" ]; then
                    RELEASE_URL="https://api.github.com/repos/$REPO/releases/latest"
                  else
                    RELEASE_URL="https://api.github.com/repos/$REPO/releases/tags/$VERSION"
                  fi
                  
                  echo "  Release API: $RELEASE_URL"
                  if [ -n "$GITHUB_TOKEN" ]; then
                    echo "  Using GitHub token for API request"
                    API_RESPONSE=$(curl -fsSL -H "Authorization: token $GITHUB_TOKEN" "$RELEASE_URL")
                  else
                    echo "  No GitHub token, using public API"
                    API_RESPONSE=$(curl -fsSL "$RELEASE_URL")
                  fi
                  
                  # For private repos, use API download URL instead of browser_download_url
                  ASSET_ID=$(echo "$API_RESPONSE" | jq -r ".assets[] | select(.name | contains(\"$ARTIFACT\")) | .id" | head -n 1)
                  
                  if [ -n "$ASSET_ID" ] && [ "$ASSET_ID" != "null" ]; then
                    # Use GitHub API to download asset (works for private repos)
                  API_DOWNLOAD_URL="https://api.github.com/repos/$REPO/releases/assets/$ASSET_ID"
                  echo "  Asset ID: $ASSET_ID"
                  echo "  API Download URL: $API_DOWNLOAD_URL"
                  download_file "$API_DOWNLOAD_URL" "/data/plugins/${NAME}.jar" || echo "Failed to download $NAME"
                  else
                    echo "✗ Could not find download URL for $NAME (artifact: $ARTIFACT)"
                    echo "  API Response: $(echo \"$API_RESPONSE\" | jq -c '.assets[].name' 2>/dev/null || echo 'Failed to parse')"
                  fi
                  
              elif [ "$TYPE" = "url" ]; then
                URL=$(yq -r ".plugins[$i].url" "$PLUGINS_CONFIG")
                download_file "$URL" "/data/plugins/${NAME}.jar" || echo "Failed to download $NAME"
                  
                else
                  echo "✗ Unknown type: $TYPE"
                fi
                
                i=$((i+1))
              done
              
              echo "=== Plugin sync completed ==="
              ls -lh /data/plugins/ || true
          volumeMounts:
            - name: world
              mountPath: /data
            - name: plugins-config
              mountPath: /config
      volumes:
        - name: world
          persistentVolumeClaim:
            claimName: {{ include "purpur.fullname" . }}-data
        - name: plugins-config
          configMap:
            name: {{ include "purpur.fullname" . }}-plugins

