apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "purpur.fullname" . }}-plugins
  labels:
    {{- include "purpur.labels" . | nindent 4 }}
data:
  plugins.yaml: |
    plugins:
      # Internal plugins (from GitHub releases)
      - name: gr-core-plugin
        type: github
        repository: BryuggemanNikita/gr-core-plugin
        version: develop  # or develop-4422338 for specific commit
        artifact: gr-core-plugin-1.0.0.jar
      
      # External plugins (direct URL)
      - name: ProtocolLib
        type: url
        url: https://github.com/dmulloy2/ProtocolLib/releases/download/5.4.0/ProtocolLib.jar
      
      # - name: LuckPerms
      #   type: url
      #   url: https://download.luckperms.net/1542/bukkit/loader/LuckPerms-Bukkit-5.4.131.jar

