{{- if .Values.minecraftNamespace.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-namespace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: kustomization
  destination:
    server: {{ .Values.destination.server | default "https://kubernetes.default.svc" }}
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}

