{{- if .Values.purpur.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: purpur
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: charts/purpur
    helm:
      releaseName: purpur
      values: |
        persistence:
          enabled: {{ .Values.purpur.persistence.enabled }}
          storageClass: {{ .Values.purpur.persistence.storageClass }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}

