image:
  repository: redis
  tag: "7-alpine"
  pullPolicy: IfNotPresent

replicas: 1

service:
  type: ClusterIP
  port: 6379

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "150m"
    memory: "128Mi"

redis:
  password: ""
  port: 6379


# Allow scheduling on single-node control-plane
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

nodeSelector: {}

