image:
  repository: ghcr.io/itzg/minecraft-server
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi

persistence:
  enabled: true
  size: 10Gi
  storageClass: local-path

service:
  type: ClusterIP
  port: 25565

env:
  TYPE: "VELOCITY"
  EULA: "TRUE"
  VELOCITY_VERSION: "LATEST"
  VELOCITY_FORWARDING_SECRET: "CHANGE_ME_STRONG_SECRET"
  ENABLE_RCON: "false"
  ONLINE_MODE: "true"

velocity:
  backendService: "purpur"
  backendPort: 25565

networkPolicy:
  enabled: true

podDisruptionBudget:
  enabled: true

hpa:
  enabled: false


