apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/balalaika7771/GR-infra.git
    targetRevision: HEAD
    path: argo-apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true


