apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velocity
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/balalaika7771/GR-infra.git
    targetRevision: HEAD
    path: charts/velocity
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

