apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velocity
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/balalaika7771/GR-infra.git
    targetRevision: HEAD
    path: charts/velocity
    helm:
      values: |
        image:
          repository: endkind/velocity
          tag: latest
          pullPolicy: IfNotPresent
        service:
          type: NodePort
          port: 25565
          nodePort: 30000
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


