apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-router.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx-router.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nginx-router.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nginx-router.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
          ports:
            - name: http
              containerPort: 80
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: config
              mountPath: /etc/nginx/conf.d/http.conf
              subPath: http.conf
            - name: config
              mountPath: /etc/nginx/conf.d/stream.conf
              subPath: stream.conf
      volumes:
        - name: config
          configMap:
            name: {{ include "nginx-router.fullname" . }}-conf

