apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-router.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx-router.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "nginx-router.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 80
      nodePort: {{ .Values.service.httpNodePort }}
    - name: minecraft
      port: {{ .Values.service.mcPort }}
      targetPort: 25565
      nodePort: {{ .Values.service.mcNodePort }}

